apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wealthfolio-data-secret
  namespace: applications

  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: wealthfolio-data-secret
  data:
  - secretKey: WF_CORS_ALLOW_ORIGINS
    remoteRef:
      key: applications/wealthfolio
      property: WF_CORS_ALLOW_ORIGINS
  - secretKey: WF_AUTH_PASSWORD_HASH
    remoteRef:
      key: applications/wealthfolio
      property: WF_AUTH_PASSWORD_HASH
  - secretKey: WF_SECRET_KEY
    remoteRef:
      key: applications/wealthfolio
      property: WF_SECRET_KEY
