---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/observability/uptime-kuma/charts/uptime-kuma
    targetRevision: HEAD
    helm:
      releaseName: uptime-kuma
      valuesObject:
        imagePullSecrets:
          - name: regcred
        image:
          registry: ${HARBOR_HOST}
          repository: dockercache/louislam/uptime-kuma
          pullPolicy: IfNotPresent
          tag: 1-debian

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  info:
  - name: releasenotes
    value: https://github.com/dirsigler/uptime-kuma-helm/releases
