---
apiVersion: v2
appVersion: "1.0"
description: Argo Workflows
name: argo-workflows
version: 1.0
dependencies:
  - name: argo-workflows
    version: "*"
    repository: https://argoproj.github.io/argo-helm
