---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capnhook
  namespace: argocd
spec:
  project: default
  source:
    path: deployments/applications/capnhook
    repoURL: 'https://github.com/sevaho/atrium'
    targetRevision: HEAD
    helm:
      releaseName: capnhook
      valuesObject:
        application:
          nameOverride: capnhook

          image:
            repository: cr.asic.li/applications/capnhook
            tag: 0.0.2

          args:
            - --serve

          service:
            type: ClusterIP
            port: 80
            targetPort: 3000

          replicaCount: 1

          extraAnnotations:
            reloader.stakater.com/auto: "true"

          ingress:
            enabled: true
            hosts:
              - alpha.capnhook.dev
            tls:
              secretName: capnhook-dev-certs

          env:
            ENVIRONMENT: ALPHA


          envFrom:
            - secretRef:
                name: capnhook-data-secret

  destination:
    server: "https://kubernetes.default.svc"
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
