apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  creationTimestamp: null
  name: capnhook-alpha
  namespace: applications
spec:
  encryptedData:
    DB_DSN: AgAOqSkC9B8a67ZUBq9Li3L/Rxh9xVvHlDdXDkPooiC4RHmD7Cbp9Y85PGwS7ZqkWURawzqkdwKG4DOj/ryJ0DMWsNNdF8iEf8K0kK+PMYZDfVPFz+QlvcdjChPwHsek/peEfLlQ2qQFrut9/jixC7ePqVP9qffKR2WA1Sr9ASE30SNQdzYNtqACMkK+hJ1QYToP7ntRONMyRpX9cDis0rv0DwNBsC2r/ZZtnRDG17/TkeD0c00WP8JX8MFzizOHMcTD0zOPFIbUsLsWclOvDwFcFB4N7abVG6uJjVh11U3Inuw1VQPr7IsoBX2gkxTD7j6W6Da2P2APsj+H11eGLiVo/wtE6xN5JLU+bt96tRKq9U4E80ku5IQQZnzmJreYKVWI3irumJbjJ5hRYc7ROgsqHHjaCG6BHdk0p8DNdxIVpfMzKFmr7HFbTN/VaYlVzK8rf39Qf89h8wyIt9hDTfK3DOeiLmGHKaA3DP/T0usaStqCSDVifCeq6rLPdgZ+eDlJU52NjJxUTRsvwVJoy1n9UVY72o2z4ihfLXDgCM1eKP+6/tKMJKx+Q/gZkm86i2mI4xcWY4OlCdf4IE46QZnlYrofvNupOUHtj6misZhTP11lMLJsYagGt777xpHc1t0kWA7DohPzjeky6+BXhICg6l/vMmCrj1KPh6G8Qpb0QkI2XYs4X82BvyuF7l0qzy6LUzOnXB2FrQRWq06pF/FCv1m2srLa4UYOm0F6FFwef6SZCAlDR6zS06cOqz6z02fGg9pnvgqu3CpCqM5ysX/ChXwwJYMQMhuCCYCK0tQ7vk+F0L/XWcLsUCsrMxhi8GQSFGX0NK4=
    JWT_SECRET: AgCUNEUqZxAVmzBrATYIH1buAIeppRrhcWJEVR/qIaVoC429cgoPLsr1qo/vqD/fhyrTjUTyq/I72/KqkYbWm23HcZT0tMt1xTGeDvK/RZsHDJmhZfGAbW/QCh4POMeyKA7gqymAijKT4gIkifN4AqSo1FqatHFik22Dt18NTyxqLegLkNQfAaJAbOjhn/7U2BuJwFAvvJt8XUmnj6YfxE/piuVEjYfTJ8yiiPM4xLg+TRHCcKqCLvM4YE+81yoVLHeAZDpKg4pfu21gSXIhbd7mvHFuYhC7fwfnV2M74KEGf0CyIiPSyC609H7LKiiB+ggY6aMCGbol4PqQrJrPqtVTNFiHrCzvFA/TazCRJjCSekHs8ABwLRmdR6rwVHeT8ToNvy2hIs5/oH1Ay8cbGqIkbZnENTrfFHyfvYPJ3szXrxZRhL9oBLa7mjZne0dXvBrZTK/j13R6v+yXAWCgHmfU7WoT2+usNkRjAMyDnWJcSnd6dUoSV2BWeP4TeT9TAPnwRwy4EpXcnwyPTVRk+IrP+OP37HAoOxmkorxN+lZdwX7L3xTykUq+ChFkDoTML3PMj20qILfAgDmXhverT6Pt8zN1A0quR5ujbKu5PqohXt5PxwjZIROMRMuXR1bIe1LXxODxYeJ0jU6mvKJ0+DSVgKOGnDSKgAssAgJphBMK4ReIz1FN5zE1YUC3RKkm65G2PPkdy2WVPxuV0SeWDvkczlSaZys5Wh010AI8Q7s5hw==
  template:
    metadata:
      creationTimestamp: null
      name: capnhook-alpha
      namespace: applications
