---
fullnameOverride: capnhook
image:
  repository: cr.asic.li/applications/capnhook
  tag: 0.0.2

args:
  - --serve

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

replicaCount: 1

extraAnnotations:
  reloader.stakater.com/auto: "true"

ingress:
  enabled: true
  hosts:
    - alpha.capnhook.dev
  tls:
    secretName: capnhook-dev-certs

env:
  ENVIRONMENT: ALPHA


envFrom:
  - secretRef:
      name: capnhook-data-secret
