kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

- name: greeting 2
  image: cr.asic.li/dockercache/alpine
  commands:
  - echo hello
  - echo world
