apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regcred
  namespace: applications
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ .registryHost }}":{"username":"{{ .registryName }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .registryName .password | b64enc }}"}}}'
  data:
  - secretKey: registryName
    remoteRef:
      key: tooling/regcred
      property: registryName
  - secretKey: registryHost
    remoteRef:
      key: tooling/regcred
      property: registryHost
  - secretKey: password
    remoteRef:
      key: tooling/regcred
      property: password
