---
apiVersion: v2
appVersion: "1.0"
description: teleport-cluster
name: teleport-cluster
version: 1.0
dependencies:
  - name: teleport-cluster
    version: "*"
    repoURL: https://charts.releases.teleport.dev
