---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/tooling/reloader
    targetRevision: HEAD
    helm:
      releaseName: reloader
      valuesObject: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://github.com/stakater/Reloader/releases
  - name: values.yaml
    value: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
