---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-assets
data:
  {{- (.Files.Glob "assets/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
data:
  config.yml: |-
    {{ .Files.Get "config.yml" }}
