---
# https://artifacthub.io/packages/helm/bitnami/clickhouse
# https://github.com/bitnami/charts/blob/main/bitnami/clickhouse/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  project: default
  source:
    chart: clickhouse
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 6.2.27
    helm:
      releaseName: clickhouse

  destination:
    server: "https://kubernetes.default.svc"
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
