apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-data-secret
  namespace: observability

  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-data-secret
  data:
  - secretKey: admin-username
    remoteRef:
      key: observability/grafana
      property: admin-username
  - secretKey: admin-password
    remoteRef:
      key: observability/grafana
      property: admin-password
