---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/observability/vector
    targetRevision: HEAD
    helm:
      releaseName: vector
      valuesObject:
        vector:
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: vector-data-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vector-data-secret
                  key: AWS_SECRET_ACCESS_KEY
          podAnnotations:
            vector.dev/exclude: 'true'
          role: Agent
          service:
            enabled: false
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/controlplane
              operator: Exists
            - effect: NoExecute
              key: node-role.kubernetes.io/etcd
              operator: Exists
          customConfig:
            data_dir: "/var/lib/vector"
            api:
              enabled: false
            sources:
              kubernetes:
                type: kubernetes_logs
              demo_syslogs:
                type: "demo_logs"
                format: "syslog"
                count: 100000
                interval: 0.1

            transforms:
              remap_kubernetes_otel:
                type: "remap"
                inputs: [kubernetes]
                source: |-
                  parsed_timestamp, err = parse_timestamp(.timestamp, "%Y-%m-%dT%H:%M:%S.%fZ")
                  if err != null {
                      log("Unable to parse timestamp, taking now(): " + err, level: "error")
                      .timestamp_nanos = to_unix_timestamp(now(), unit: "nanoseconds")

                  } else {
                      .timestamp_nanos = to_unix_timestamp(parsed_timestamp, unit: "nanoseconds")
                  }
                  .resource_attributes = .kubernetes
                  .service_name = .kubernetes.pod_name

                  .attributes.stream = .stream
                  .resource_attributes.file = .file

                  parsed_json, err = parse_json(.message)
                  if err != null {
                      .body.message = .message
                  } else {
                      .body = parsed_json

                      levelinfo = null
                      if exists(parsed_json.level) {
                          levelinfo = parsed_json.level
                      } else if exists(.body.level) {
                          levelinfo = parsed_json.levelname
                      }
                      .severity_text = if includes(["emerg", "err", "crit", "alert", "error", "ERR", "ERROR"], levelinfo) {
                          "ERROR"
                      } else if includes(["warn", "warning", "WARN", "WARNING"], levelinfo) {
                          "WARNING"
                      } else if includes(["debug", "DEBUG"], levelinfo) {
                          "DEBUG"
                      } else if includes(["info", "INFO"], levelinfo) {
                          "INFO"
                      } else {
                          levelinfo
                      }

                  }
                  .id = uuid_v7()

                  del(.kubernetes)
                  del(.timestamp)
                  del(.source_type)
                  del(.stream)
                  del(.message)
                  del(.file)


            sinks:
              s3:
                type: aws_s3
                inputs:
                  - kubernetes
                endpoint: ${AWS_S3_ENDPOINT}
                bucket: ${AWS_S3_BUCKET}
                region: ${AWS_S3_REGION}
                key_prefix: vector/logs/kubernetes/hetzner/year=%Y/month=%m/day=%d
                encoding:
                  codec: json
              quickwit_logs:
                type: "http"
                method: "post"
                inputs:
                  - remap_kubernetes_otel
                encoding:
                  codec: json
                framing:
                  method: "newline_delimited"
                uri: "http://quickwit-indexer:7280/api/v1/vector-otel-0.8/ingest"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  info:
  - name: releasenotes
    value: https://github.com/vectordotdev/vector/releases
  - name: values.yaml
    value: https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/values.yaml
---
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY::BASE64}
  AWS_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_KEY::BASE64}
kind: Secret
metadata:
  name: vector-data-secret
  namespace: observability
type: Opaque
