---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/observability/vector
    targetRevision: HEAD
    helm:
      releaseName: vector
      valuesObject:
        vector:
          podAnnotations:
            vector.dev/exclude: 'true'
          role: Agent
          service:
            enabled: false
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/controlplane
              operator: Exists
            - effect: NoExecute
              key: node-role.kubernetes.io/etcd
              operator: Exists
          customConfig:
            data_dir: "/var/lib/vector"
            api:
              enabled: false
            sources:
              kubernetes:
                type: kubernetes_logs

            transforms:
              remap_kubernetes_otel:
                type: "remap"
                inputs: [kubernetes]
                source: |-
                  parsed_timestamp, err = parse_timestamp(.timestamp, "%Y-%m-%dT%H:%M:%S.%fZ")
                  if err != null {
                      log("Unable to parse timestamp, taking now(): " + err, level: "error")
                      .timestamp_nanos = to_unix_timestamp(now(), unit: "nanoseconds")

                  } else {
                      .timestamp_nanos = to_unix_timestamp(parsed_timestamp, unit: "nanoseconds")
                  }
                  .resource_attributes = .kubernetes
                  .service_name = .kubernetes.pod_name

                  .attributes = .kubernetes
                  .attributes.cluster = "wegroup-hetzner-server-1"
                  .resource_attributes.file = .file

                  .body.stream = .stream

                  level = null
                  msg = slice(.message, 0, 100) ?? ""

                  # 1. Try json
                  parsed_json, err = parse_json(.message)
                  if err == null {
                      level = parsed_json.level || parsed_json.levelname || parsed_json.severity || parsed_json.log_level || null
                      .body.message = .message
                      .message = parsed_json.message || parsed_json.msg || parsed_json.log
                  }

                  # 2. Try logfmt
                  if level == null {
                      parsed = parse_logfmt(msg) ?? {}
                      level = parsed.level ||  parsed.severity || null
                  }

                  # 3. Try syslog
                  if level == null {
                      parsed = parse_syslog(msg) ?? {}
                      level = parsed.severity || null
                  }

                  # 4. Try klog
                  if level == null {
                      parsed = parse_klog(msg) ?? {}
                      level = parsed.level || null
                  }


                  # 5. Try parse groks
                  if level == null {
                      parsed = parse_groks(msg,
                      	patterns: [
                          "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}",
                          "%{DATA:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}"

                        ]
                      ) ?? {}
                      level = parsed.level || null
                  }

                  # 6. Normalize
                  if level != null {
                    if includes(["info", "INFO", "inf", "INF", "notice", "NOTICE", "[info]", "[INFO]", "5", "6"], level) {
                        .severity_text = "info"
                    } else if includes(["emerg", "fatal", "crit", "alert", "FATAL", "critical", "ALERT", "CRITICAL", "[critical]", "[CRITICAL]", "0", "1", "2"], level) {
                        .severity_text = "critical"
                    } else if includes(["err", "eror", "error", "ERR", "ERROR", "[error]", "[ERROR]", "3"], level) {
                        .severity_text = "error"
                    } else if includes(["warn", "warning", "war", "WARN", "WARNING", "WAR", "[WARN]", "[WARNING]", "[warn]", "4"], level) {
                        .severity_text = "warning"
                    } else if includes(["debug", "DEBUG", "deb", "DEB", "[debug]", "[DEBUG]", "7"], level) {
                        .severity_text = "debug"
                    } else {
                        .severity_text = "unknown"
                    }
                  } else if .stream == "stderr" {
                    .severity_text = "error"
                  } else {
                    .severity_text = "unknown"
                  }

                  if .body.message != null {
                    .message = upcase(.severity_text) + " " + to_string(.message) ?? "NO MESSAGE BODY"
                  }

                  .id = uuid_v7()

                  del(.kubernetes)
                  del(.timestamp)
                  del(.source_type)
                  del(.stream)
                  del(.file)


            sinks:
              quickwit_logs:
                type: "http"
                method: "post"
                inputs:
                  - remap_kubernetes_otel
                encoding:
                  codec: json
                framing:
                  method: "newline_delimited"
                uri: "http://quickwit-indexer:7280/api/v1/vector-otel-0.8/ingest"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  info:
  - name: releasenotes
    value: https://github.com/vectordotdev/vector/releases
  - name: values.yaml
    value: https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/values.yaml
