---
fullnameOverride: web-asic-li

image:
  repository: cr.asic.li/applications/web.asic.li
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

pvc:
  enabled: true

ingress:
  enabled: true
  hosts:
    - asic.li
    - web.asic.li
  tls:
    secretName: web-asic-li-certs
