---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/kubeseal/sealed-secrets
    targetRevision: HEAD
    helm:
      releaseName: sealed-secrets
      valuesObject:
        sealed-secrets:
          image:
            registry: docker.io
            repository: bitnami/sealed-secrets-controller
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  info:
  - name: releasenotes
    value: https://github.com/bitnami-labs/sealed-secrets/releases
  - name: values.yaml
    value: https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
