---
# https://github.com/woodpecker-ci/helm/blob/main/charts/woodpecker/README.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: woodpecker
  namespace: argocd
spec:
  project: default
  source:
    chart: woodpecker
    repoURL: https://woodpecker-ci.org/
    targetRevision: 1.6.0
    helm:
      releaseName: woodpecker
      valuesObject:
        agent:
          enabled: true
          extraSecretNamesForEnvFrom: ["woodpecker-agent-data-secret"]
          env:
            WOODPECKER_LOG_LEVEL: debug
        server:
          enabled: true
          env:
            WOODPECKER_HOST: https://${TELEPORT_WOODPECKER_HOST}
            WOODPECKER_ADMIN: sevaho
            WOODPECKER_LOG_LEVEL: debug
            WOODPECKER_BACKEND_K8S_STORAGE_CLASS: longhorn
            WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
          extraSecretNamesForEnvFrom: ["woodpecker-server-data-secret"]

  destination:
    server: "https://kubernetes.default.svc"
    namespace: woodpecker
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: v1
data:
  WOODPECKER_HOST: ${WOODPECKER_HOST::BASE64}
  WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET::BASE64}
kind: Secret
metadata:
  name: woodpecker-agent-data-secret
  namespace: woodpecker
type: Opaque
---
apiVersion: v1
data:
  WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET::BASE64}
  WOODPECKER_DATABASE_DATASOURCE: ${WOODPECKER_DATABASE_DATASOURCE::BASE64}
  WOODPECKER_DATABASE_DRIVER: ${WOODPECKER_DATABASE_DRIVER::BASE64}
  WOODPECKER_GITHUB: dHJ1ZQ== # true
  WOODPECKER_GITHUB_CLIENT: ${WOODPECKER_GITHUB_CLIENT_ID::BASE64}
  WOODPECKER_GITHUB_SECRET: ${WOODPECKER_GITHUB_CLIENT_SECRET::BASE64}
  WOODPECKER_HOST: ${WOODPECKER_HOST::BASE64}
  WOODPECKER_WEBHOOK_HOST: ${WOODPECKER_WEBHOOK_HOST::BASE64}
kind: Secret
metadata:
  name: woodpecker-server-data-secret
  namespace: woodpecker
type: Opaque
