apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-data-secret
  namespace: applications

  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: firefly-data-secret
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: applications/firefly
      property: DB_HOST
  - secretKey: DB_USERNAME
    remoteRef:
      key: applications/firefly
      property: DB_USERNAME
  - secretKey: APP_PASSWORD
    remoteRef:
      key: applications/firefly
      property: APP_PASSWORD
  - secretKey: DB_PASSWORD
    remoteRef:
      key: applications/firefly
      property: DB_PASSWORD
