---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/tooling/external-secrets
    targetRevision: HEAD
    helm:
      releaseName: external-secrets
      valuesObject:
        external-secrets:
          grafanaDashboard:
            enabled: false
          webhook:
            certManager:
              enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://github.com/external-secrets/external-secrets/releases
  - name: values.yaml
    value: https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml
