# Checkout install script in vault directory to configure auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: applications
---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-sa-secret
  namespace: applications
  annotations:
    kubernetes.io/service-account.name: external-secrets-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-vault-role
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "serviceaccounts/token"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-vault-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-vault-role
subjects:
  - kind: ServiceAccount
    name: external-secrets-sa
    namespace: applications
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: applications
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://vault.tooling.svc.cluster.local:8200"
      path: "applications"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-vault-role"
          serviceAccountRef:
            name: "external-secrets-sa"
