---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/tooling/metabase
    targetRevision: HEAD
    helm:
      releaseName: metabase
      valuesObject:
        metabase:
          replicaCount: 1
          siteUrl: ${METABASE_HOST}
          database:
            type: postgres
            existingSecret: metabase-data-secret
            existingSecretConnectionURIKey: connectionURI
            existingSecretEncryptionKeyKey: encryptionKey


  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy: {}

  info:
  - name: releasenotes
    value: https://github.com/metabase/metabase/releases
  - name: values.yaml
    value: https://artifacthub.io/packages/helm/pmint93/metabase
