---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/tooling/headlamp
    targetRevision: HEAD
    helm:
      releaseName: headlamp
      valuesObject: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://github.com/kubernetes-sigs/headlamp/releases
  - name: values.yaml
    value: https://github.com/kubernetes-sigs/headlamp/blob/main/charts/headlamp/values.yaml
