---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
spec:
  project: default
  source:
    path: deployments/tooling/homer
    repoURL: 'https://github.com/sevaho/atrium'
    targetRevision: HEAD
    helm:
      releaseName: homer
      valuesObject:
        example:
          nameOverride: homer
          replicaCount: 1

          env:
            TZ: "Europe/Brussels"

          image:
            repository: ${HARBOR_HOST}/dockercache/b4bz/homer
            tag: latest

          imagePullSecrets: [regcred]

          service:
            type: ClusterIP
            port: 80
            targetPort: 8080

          volumeMounts:
            - name: homer-config
              mountPath: "/www/assets/config.yml"
              subPath: config.yml
              readOnly: true

            - name: homer-assets-data
              mountPath: "/www/assets/data"
              readOnly: true

          volumes:
            - name: homer-config
              configMap:
                name: homer-config
            - name: homer-assets-data
              configMap:
                name: homer-assets-data

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://github.com/bastienwirtz/homer/releases
  - name: values.yaml
    value: https://github.com/djjudas21/charts/blob/main/charts/homer/values.yaml
  - name: configuration
    value: https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: tooling
data:
  config.yml: |-
    title: "The One Pager"

    header: false
    footer: ''

    columns: "4"

    stylesheet:
      - 'assets/data/catppuccin-macchiato.css'

    defaults:
      layout: columns
      colorTheme: dark

    # message:
    #   style: "is-warning"
    #   title: "Optional message!"
    #   icon: "fa fa-exclamation-triangle"
    #   content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    links:
      - name: "Link 1"
        icon: "fab fa-github"
        url: "https://github.com/bastienwirtz/homer"
        target: "_blank" # optional html tag target attribute
      - name: "link 2"
        icon: "fas fa-book"
        url: "https://github.com/bastienwirtz/homer"

    services:
      - name: "Public"
        items:
          - name: "Goforms"
            subtitle: "Posting forms as mail"
            tag: "application"
            keywords: "insights"
            url: https://goforms.dev
          - name: "RSS"
            subtitle: "Miniflux RSS."
            tag: "application"
            keywords: "rss"
            url: https://rss.asic.li
      - name: "Tools"
        items:
          - name: "Metabase"
            logo: "assets/data/metabase.svg"
            subtitle: "Analytics and Insights"
            tag: "internal"
            keywords: "insights"
            url: https://${METABASE_HOST}
          - name: "Harbor"
            logo: "assets/data/harbor.svg"
            subtitle: "Status page"
            tag: "internal"
            keywords: "insights"
            url: https://${HARBOR_INTERNAL_HOST}
          - name: "ArgoCD"
            logo: "assets/data/argo-cd.svg"
            subtitle: "CD platform"
            tag: "internal"
            keywords: "cd"
            url: https://${ARGOCD_HOST}
          - name: "ArgoCD Workflows"
            logo: "assets/data/argo-cd.svg"
            subtitle: "Workflow engine"
            tag: "internal"
            keywords: "workflow"
            url: https://${ARGO_WORKFLOWS_HOST}
          - name: "Vault"
            logo: "assets/data/vault.svg"
            subtitle: "Hashicorp Vault"
            tag: "internal"
            keywords: "vault"
            url: https://${VAULT_HOST}
          - name: "FireFly"
            logo: "assets/data/firefly.svg"
            subtitle: "Personal finance"
            tag: "internal"
            keywords: "finance"
            url: https://${FIREFLY_III_HOST}
          - name: "PGhero"
            logo: "assets/data/pghero.svg"
            subtitle: "Insights into postgres queries"
            tag: "internal"
            keywords: "postgres"
            url: https://${PGHERO_HOST}
          - name: "WoodPecker CI"
            logo: "assets/data/woodpecker-ci.svg"
            subtitle: "CI"
            tag: "internal"
            keywords: "ci"
            url: https://${WOODPECKER_HOST}

      - name: "Observability"
        items:
          - name: "Gatus"
            logo: "assets/data/gatus.svg"
            subtitle: "Status page"
            tag: "internal"
            keywords: "status page"
            url: https://${GATUS_HOST}

          - name: "Grafana"
            logo: "assets/data/grafana.svg"
            subtitle: "Metrics"
            tag: "internal"
            keywords: "grafana metrics"
            url: https://${GRAFANA_HOST}

          - name: "Netdata"
            logo: "assets/data/netdata.svg"
            subtitle: "Netdata"
            tag: "internal"
            keywords: "netdata metrics"
            url: https://${NETDATA_HOST}

          - name: "Coroot"
            logo: "assets/data/coroot.svg"
            subtitle: "Coroot"
            tag: "internal"
            keywords: "coroot metrics"
            url: https://${COROOT_HOST}

          - name: "Umami"
            logo: "assets/data/umami.svg"
            subtitle: "Website analytics"
            tag: "internal"
            keywords: "website analytics"
            url: https://${UMAMI_INTERNAL_HOST}

          - name: "Headlmap"
            logo: "assets/data/headlamp.svg"
            subtitle: "Kubernetes insights"
            tag: "internal"
            keywords: "kubernetes analytics"
            url: https://${HEADLAMP_HOST}
