---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
spec:
  project: default
  source:
    path: deployments/tooling/homer
    repoURL: 'https://github.com/sevaho/atrium'
    targetRevision: HEAD
    helm:
      releaseName: homer
      valuesObject:
        example:
          nameOverride: homer
          replicaCount: 1

          env:
            TZ: "Europe/Brussels"

          image:
            repository: cr.asic.li/dockercache/b4bz/homer
            tag: latest

          imagePullSecrets: [regcred]

          service:
            type: ClusterIP
            port: 80
            targetPort: 8080

          volumeMounts:
            - name: homer-config
              mountPath: "/www/assets/config.yml"
              subPath: config.yml
              readOnly: true

            - name: homer-assets-logos
              mountPath: "/www/assets/data"
              readOnly: true

          volumes:
            - name: homer-config
              configMap:
                name: homer-config
            - name: homer-assets-data
              configMap:
                name: homer-assets-data

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://github.com/bastienwirtz/homer/releases
  - name: values.yaml
    value: https://github.com/djjudas21/charts/blob/main/charts/homer/values.yaml
  - name: configuration
    value: https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: tooling
data:
  config.yml: |-
    title: "App dashboard"

    header: false
    footer: ''

    stylesheet:
      - 'assets/data/catppuccin-macchiato.css'

    defaults:
      layout: columns
      colorTheme: auto

    message:
      style: "is-warning"
      title: "Optional message!"
      icon: "fa fa-exclamation-triangle"
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    links:
      - name: "Link 1"
        icon: "fab fa-github"
        url: "https://github.com/bastienwirtz/homer"
        target: "_blank" # optional html tag target attribute
      - name: "link 2"
        icon: "fas fa-book"
        url: "https://github.com/bastienwirtz/homer"

    services:
      - name: "Application"
        icon: "fas fa-code-branch"
        items:
          - name: "Gatus"
            logo: "assets/logos/gatus.svg"
            subtitle: "Status page"
            tag: "internal"
            keywords: "status page"
            url: https://${GATUS_HOST}

          - name: "Gatus as type"
            type: "gatus"
            logo: "assets/logos/gatus.svg"
            subtitle: "Status page"
            tag: "internal"
            keywords: "status page"
            url: http://gatus.observability.svc.cluster.local


          - name: "Another one"
            logo: "assets/tools/sample2.png"
            subtitle: "Another application"
            tag: "app"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "#"
      - name: "Other group"
        icon: "fas fa-heartbeat"
        items:
          - name: "Pi-hole"
            logo: "assets/tools/sample.png"
            # subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
            tag: "other"
            url: "http://192.168.0.151/admin"
            type: "PiHole"
            target: "_blank" # optional html a tag target attribute
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
    # background: red # optional color for card to set color directly without custom stylesheet
