---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/tooling/homer
    targetRevision: HEAD
    helm:
      releaseName: homer
      valuesObject:
        homer: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://github.com/bastienwirtz/homer/releases
  - name: values.yaml
    value: https://github.com/djjudas21/charts/blob/main/charts/homer/values.yaml
