---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glitchtip
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/tooling/glitchtip
    targetRevision: HEAD
    helm:
      releaseName: glitchtip
      valuesObject: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://gitlab.com/glitchtip/glitchtip-backend/-/releases
  - name: values.yaml
    value: https://gitlab.com/glitchtip/glitchtip-helm-chart/-/blob/master/charts/glitchtip/values.yaml?ref_type=heads
