---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/cert-manager/external-dns
    targetRevision: HEAD
    helm:
      releaseName: external-dns
      valuesObject:
        external-dns:
          logLevel: info
          sources:
            - service
            # - ingress # This does not work as expected
          provider:
            name: digitalocean
          env:
            - name: DO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: external-dns-data-secret
                  key: DO_TOKEN

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  info:
  - name: releasenotes
    value: https://github.com/kubernetes-sigs/external-dns/releases
  - name: values.yaml
    value: https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
---
apiVersion: v1
data:
  DO_TOKEN: ${DO_TOKEN::BASE64}
kind: Secret
metadata:
  name: external-dns-data-secret
  namespace: cert-manager
type: Opaque
