---
apiVersion: v2
appVersion: "1.0"
description: external-dns
name: external-dns
version: 1.0
dependencies:
  - name: external-dns
    version: "*"
    repository: https://kubernetes-sigs.github.io/external-dns
