apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-infrastructure-repository
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: git-infrastructure-repository
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: argocd/argocd
      property: GIT_REPOSITORY_SSH_PRIVATE_KEY
  - secretKey: type
    remoteRef:
      key: argocd/argocd
      property: GIT_REPOSITORY_TYPE
  - secretKey: url
    remoteRef:
      key: argocd/argocd
      property: GIT_REPOSITORY_URL
