apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientID: AgAZJFS2X1nqwWRgo75l972Hly+SZ/0BrbXvUh4UgZwRhGbS5XuxxxlR19jYaI53LkCct0lVIyCnCCbKvTvgjzvBRDRsYaVQWPaLAZ4e2BEZ4LT0d9cDucjj4tVq0xEJsXJm4Jc0Fba+/LwxmoNuPQ6Uvl/qTLiy3MI0ndSccwKt90S+AgWD4mwhpc+BOyOCTXzzYmI7mSoS/u2NzMXDUM8nM8l6CTWFbVRWKyuFe8GUEEB1ypgItjrPlLjbClRptx6pb1uyIafMqF9Y1XHvxWGRE+y0anUMvxQ8LP3+o4ThjMcMvNk2zYfZenC1YCAo46od4RZPsm0cYr9ITBp3HDVnj3GheT+6g3lzNzTzUvT90We6fDPTYZoXGcqpAG4iB2Dz9KE4czUngVV08sEsXLE2kZ5a1TfuclR5RT+J4Xg+v85FRwAQlQPYMMYA/oovRhofjNd/yIXXGYo5woVjVgDt64Z60T3v1o7T5jr7y1irRYbG0cHc3pgxaj+JCWSjM1ddiEmVikRgx0vhKMdzZlRHbXI8tCCjnuYmtKZthcxBAXQ6OLcYNAmgLlLEqp7C/bCOeBb8qmVxiilPt9R8COaetXouPLwN0GM/BODJxhsIltI0T+jeFubrobewkD61Uk+a0jfaVosgIKSijUD/2bRvlt6Dx7bizyqkrkXiy3DxAaeywddYrpmiDT49d8nneKrP4iyB3M8rigEmk3RzJy1Thcci/g==
    dex.github.clientSecret: AgAKC9i5NBEJEZxaDn4EsV7SBpVL5WOdN4D2FUlRZd2T2h9YULtlbqxhN0NCV2to8V/4Tp1CLhV2EP9dbg5v2tmX6XvHSzKw4iTEjeCks2DUv5Vu7wLshqxqRtq8f5GFZflwhhyC+5+Akn8yI3LqvkjcOVzGjAV2GmupG2YbRIGy6F7JPv13su9XlyNSMF+4HKhDhf9XwD55x5XXSFPDSWYNe6hey0deWyuXl5Xu9FDHDAQwQjLZRomXPcJteVeQaFifDJxppueuOXTvOH80D8yQnZYgfAbgea6dMtMTRh/T5g1jGypJzdo5uHscYFwln5M7xWKI4/aSmUFenc229jPmxrVaF0Fy9Z6G3ySQCO5jOXqWwWIZgxWFoTRadiWCeHqB01h9EWGybx15TgHdSU2nVLpcPUELhQTLtK8s8hk1T3UopTaBVXR+A/kBwXVCccfqKZ+pXaNmGWQ6xWitDW6504rKC9cDnnJpDysu3N1oMZUYsRhfgaSIzB5ApZiSekVUs7bkxnOvG6YKtbmHLisZbF/Et4gUfpbzu0u2Ah2UGOaQcK4NUmeRANpgI3876vp8ZJWk1MDvzJJdaI3sXYnsTW59bbXQM73RiWwDttwuQqkZsNjUPI85ZPGibevqz84rdR6jF/zohvgbQYG+AceaAkUp7LedvCW6qNFOOAz34TeCgFbfnIm1tzSs/OArLEBEkopxufD/1J3/tfRkR4u6oLZagTrK30BgsM7v2U7tYU/rS9X1nsB+
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
