---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickwit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/observability/quickwit
    targetRevision: HEAD
    helm:
      releaseName: quickwit
      valuesObject:
        quickwit:
          environment:
            RUST_LOG: warning
            QW_DISABLE_TELEMETRY: "1"
            NO_COLOR: "1"

          environmentFrom:
            - secretRef:
                name: quickwit-data-secret

          # Prometheus metrics
          serviceMonitor:
            enabled: true

          config:
            default_index_root_uri: s3://data-ee808bd/quickwit-indexes

            # Storage configuration.
            storage:
              s3:
                endpoint: https://fra1.digitaloceanspaces.com
                region: fra1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  info:
  - name: releasenotes
    value: https://github.com/quickwit-oss/quickwit/releases
  - name: values.yaml
    value: https://github.com/quickwit-oss/helm-charts/blob/main/charts/quickwit/values.yaml
