apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quickwit-data-secret
  namespace: observability

  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: quickwit-data-secret
  data:
  - secretKey: QW_METASTORE_URI
    remoteRef:
      key: observability/quickwit
      property: QW_METASTORE_URI

  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: observability/quickwit
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: observability/quickwit
      property: AWS_SECRET_ACCESS_KEY
