---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/kube-system/metrics-server
    targetRevision: HEAD
    helm:
      releaseName: metrics-server
      valuesObject:
        metrics-server:
          apiService:
            create: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://github.com/kubernetes-sigs/metrics-server/releases
