---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/observability/gatus
    targetRevision: HEAD
    helm:
      releaseName: gatus
      valuesObject:
        gatus:
          config:
            # storage:
            #   type: postgres
            #   path: "postgres://user:password@127.0.0.1:5432/gatus?sslmode=disable"
            endpoints:
              - name: sevaho.io
                url: https://sevaho.io
                interval: 60s
                conditions:
                  - "[STATUS] == 200"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  info:
  - name: releasenotes
    value: https://github.com/TwiN/gatus/releases
  - name: values.yaml
    value: https://github.com/TwiN/helm-charts/blob/master/charts/gatus/values.yaml
  - name: configuration
    value: https://github.com/TwiN/gatus?tab=readme-ov-file#configuration
