apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-data-secret
  namespace: observability

  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: gatus-data-secret
  data:
  - secretKey: DB_DSN
    remoteRef:
      key: observability/gatus
      property: DB_DSN
  - secretKey: TELEGRAM_CHAT_ID
    remoteRef:
      key: observability/gatus
      property: TELEGRAM_CHAT_ID
  - secretKey: TELEGRAM_BOT_TOKEN
    remoteRef:
      key: observability/gatus
      property: TELEGRAM_BOT_TOKEN
