---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keep
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/observability/keep
    targetRevision: HEAD
    helm:
      releaseName: keep
      valuesObject:
        keep:
          namespace: observability
          global:
            ingress:
              enabled: false
          backend:
            waitForDatabase:
              enabled: false
            env:
              - name: DATABASE_CONNECTION_STRING
                value: ${KEEP_DB_DSN}
          database:
            enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  info:
  - name: releasenotes
    value: https://github.com/keephq/keep/releases
  - name: values.yaml
    value: https://github.com/keephq/helm-charts/blob/main/charts/keep/values.yaml
